2025-04-14 00:18:26,930 ERROR: Exception on /qr/generar [POST] [in /Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/Documents/Develop/backup/dinqr/backend/routes/qr_routes.py", line 75, in generar_codigos_qr
    return jsonify(generar_qr(ids))
                   ^^^^^^^^^^^^^^^
  File "/Users/mcc/Documents/Develop/backup/dinqr/backend/services/qr_service.py", line 42, in generar_qr
    server_domain = obtener_configuracion("serverDomain")  # Obtener serverDomain
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/Documents/Develop/backup/dinqr/backend/services/qr_service.py", line 20, in obtener_configuracion
    cursor.execute("SELECT value FROM settings WHERE key = ?", (clave,))
psycopg2.errors.SyntaxError: syntax error at end of input
LINE 1: SELECT value FROM settings WHERE key = ?
                                                ^

2025-04-14 00:18:35,250 ERROR: Exception on /qr/generar [POST] [in /Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/Documents/Develop/backup/dinqr/backend/routes/qr_routes.py", line 75, in generar_codigos_qr
    return jsonify(generar_qr(ids))
                   ^^^^^^^^^^^^^^^
  File "/Users/mcc/Documents/Develop/backup/dinqr/backend/services/qr_service.py", line 42, in generar_qr
    server_domain = obtener_configuracion("serverDomain")  # Obtener serverDomain
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/Documents/Develop/backup/dinqr/backend/services/qr_service.py", line 20, in obtener_configuracion
    cursor.execute("SELECT value FROM settings WHERE key = ?", (clave,))
psycopg2.errors.SyntaxError: syntax error at end of input
LINE 1: SELECT value FROM settings WHERE key = ?
                                                ^

2025-04-14 00:18:43,017 ERROR: Exception on /qr/descargar/101 [GET] [in /Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/Documents/Develop/backup/dinqr/backend/routes/qr_routes.py", line 80, in descargar_codigo_qr
    return send_file(descargar_qr(contact_id), as_attachment=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/Documents/Develop/backup/dinqr/backend/services/qr_service.py", line 71, in descargar_qr
    cursor.execute("SELECT archivo_qr FROM qr_codes WHERE contact_id = ?", (contact_id,))
psycopg2.errors.SyntaxError: syntax error at end of input
LINE 1: SELECT archivo_qr FROM qr_codes WHERE contact_id = ?
                                                            ^

2025-04-14 00:18:48,674 ERROR: Exception on /qr/descargar/123 [GET] [in /Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/Documents/Develop/backup/dinqr/backend/routes/qr_routes.py", line 80, in descargar_codigo_qr
    return send_file(descargar_qr(contact_id), as_attachment=True)
                     ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/Documents/Develop/backup/dinqr/backend/services/qr_service.py", line 71, in descargar_qr
    cursor.execute("SELECT archivo_qr FROM qr_codes WHERE contact_id = ?", (contact_id,))
psycopg2.errors.SyntaxError: syntax error at end of input
LINE 1: SELECT archivo_qr FROM qr_codes WHERE contact_id = ?
                                                            ^

2025-04-14 00:18:59,458 ERROR: Exception on /qr/generar [POST] [in /Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py:875]
Traceback (most recent call last):
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask_cors/extension.py", line 176, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py", line 917, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/.virtualenvs/sgha/lib/python3.12/site-packages/flask/app.py", line 902, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/Documents/Develop/backup/dinqr/backend/routes/qr_routes.py", line 75, in generar_codigos_qr
    return jsonify(generar_qr(ids))
                   ^^^^^^^^^^^^^^^
  File "/Users/mcc/Documents/Develop/backup/dinqr/backend/services/qr_service.py", line 42, in generar_qr
    server_domain = obtener_configuracion("serverDomain")  # Obtener serverDomain
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/mcc/Documents/Develop/backup/dinqr/backend/services/qr_service.py", line 20, in obtener_configuracion
    cursor.execute("SELECT value FROM settings WHERE key = ?", (clave,))
psycopg2.errors.SyntaxError: syntax error at end of input
LINE 1: SELECT value FROM settings WHERE key = ?
                                                ^

